### PR TITLE
Support for Java 14 & Spring Boot 2.3.0

### PR DESCRIPTION
**Pull request by mdjimy**
Project was updated so it now supports Java 8 - 14 and Spring Boot 2.0.X - 2.3.X.
Project dependencies were reorganized in order to maximally minimalize amount of transitive dependencies.
There is a few breaking changes thought:
1) Repositories are now using depenenci injection via Constructor as `@PostConstruct` was removed in new Java versions. (To be hones I like it this way more then to inject dependencies via setters).
2) `javax.persistence-api` scope was changed to `provided`. Reason for this decision is that there exists various implementations (and versions) of this library (eg. `hibernate-jpa-2.1-api` etc) so I beleave that every project using this library should define implementation it needs.
3) Some dependencies were removed `commons-io` (not used) and `commons-lan3` (not needed)

### CODE REVIEW

**Comment by rmalchow** [comment]
hi,

this is great. thank you very much! this merged and built as v0.53 one thing i changed is to not have the constructor - doing a getParsedEntity() instead (and once it is parsed, keep it). this removed everything that would be a breaking change (i dont think the javax-persistence dependency counts) ... anyways - what do you think of this solution to the @PostContruct issue? not sure how much we would benefit from the `finals` ...

.rm

**Comment by mdjimy** [comment]
:man_facepalming: I was so focusing on replacing `@PostContruct` with alternative implementation that I've missed the fact, that `getParsedEntity()` does not have to be annotated as `@PostContruct` at all. XD
Anyway, there is several ways how to deal with missing `@PostConstruct` and `@PreDestroy` which were removed in Java 11. The simplest of them is of course to add dependency `javax.annotation:javax.annotation-api` to your project. Secon option might be to make use of Spring `InitializingBean` and `DisposableBean` interfaces.

Concerning autowired constructors. This is best practice I've adopted and that can be seen in many projects. In this example (`AbstractMappingRepository`):
1) `DataSource` is mandatory dependency without which will this repository not work. But that fact is in current implementation hidden as there is no constructor accepting as it's injected into bean property. I like to write object the way so you can just from looking on it's API say how to use it without need to get familiar with it's internal implementation.
2) Passing dependencies via constructor also helps significantly in tests. As it's now you have to use in unit test reflection to make `dataSource` accessible in order to set it which is not nice or to provide setters which breaks encapsulation.
3) It's not possible to inject different implementation / instance of `DataSource` to this bean then is registered in application context. (this might be again eg. useful for tests where I want to eg. mock / replace it with alternative implementation).

Concerning finals.
1) It helps readability & understanding how you should manipulate with that property.
2) You will not override it by accident
Here eg. again `DataSource`. You really should not allow to override this property once this object was initialized as it might lead to unexpected errors (usually eg. due to concurrency etc).

**Comment by rmalchow** [comment]
yep - i agree with your points for the most part - what i am trying to do is to not HAVE to add delegate constructors all over the place. for the java style, i think i can really learn from you guys, especially when its about "the new shit" - the challenge here is to avoid breaking changes. did you already implement the extra contructors everywhere? then maybe we can have both - empty _and_ with DataSource? that way, i would have to go through all my repo classes and add a constructor everywhere.

**Comment by mdjimy** [comment]
Well I was considering whether to do this BC or not, in the end decided to **try** to submit it in pull request but I don't insist on it. Just thought it might be nice to improve encapsulation of this repository, but if you are strongly dependant on this behaviour than it might not be worth that hassle.

Thankfully, this pull request serves as a preparation (one of prerequisits) for out upcoming attempt to upgrade our apps to latest Spring Boot and eventually also to move to Java 11 so these changes were not yet integrated into our codebase.

Having no-arg & arg constructors might help a thing a bit but to be honest I've newer tried to do it so I'm not sure how it would behave (eg. `@Autowired` might teoretically overwrite value passed via constructor).

**Comment by rmalchow** [comment]
ok, so maybe no double constructors. can you try the current version (0.53 i believe) and check if that works for you? it does remove the @PostContruct, but keeps the empty constructor.

for all practival purposes, `<init> (DataSource)` and `<init> () + @Autowired` does the same thing (i.e. fail if it isnt there). one concert could be what happens outside of spring ... but then again ... that's probably not a realistic scenario anyways.

**Pull request merged**
